contest_list = {
    'highest_qb_points' : {'position': ['QB'], 'stat': ['']},
    'total_rb_points' : {'position': ['RB'], 'stat': ['']},
    'total_wr_points' : {'position': ['WR'], 'stat': ['']},
    'highest_te_points' : {'position': ['TE'], 'stat': ['']},
    'highest_flex_points' : {'position': ['RB/WR/TE'], 'stat': ['']},
    'total_de_points' : {'position': ['DE'], 'stat': ['']},
    'total_lb_points' : {'position': ['LB'], 'stat': ['']},
    'total_punter_points' : {'position': ['P'], 'stat': ['']},
    'highest_hc_points' : {'position': ['HC'], 'stat': ['']},
    'highest_single_starter_points' : {'position' : ['QB', 'RB', 'WR','TE', 'RB/WR/TE','DE', 'LB', 'P', 'HC'], 'stat': [''], 'single': True},
    'highest_bench_player_points' : {'position': ['BE'], 'stat': [''], 'single': True},
    'total_defensive_points' : {'position': ['DE','LB'], 'stat': ['']},
    'total_offensive_points_flex' : {'position': ['QB', 'RB', 'WR','TE', 'RB/WR/TE'], 'stat': ['']},
    'total_offensive_points_no_flex' : {'position': ['QB', 'RB', 'WR','TE'], 'stat': ['']},
    'total_points' : {'position' : ['QB', 'RB', 'WR','TE', 'RB/WR/TE','DE', 'LB', 'P', 'HC'], 'stat': ['']},
    'most_qb_passing_yards' : {'position': ['QB'], 'stat': ['passingYards']},
    'total_receptions_by_wr' : {'position': ['WR'], 'stat': ['receivingReceptions']},
    'total_receptions_by_rb' : {'position': ['RB'], 'stat': ['receivingReceptions']},
    'total_receptions_by_wr_and_rb' : {'position': ['WR', 'RB'], 'stat': ['receivingReceptions']},
    'total_punts_downed_within_20' : {'position': ['P'], 'stat': ['puntsInsideThe20']},
    'total_punter_yards' : {'position': ['P'], 'stat': ['puntYards']},
    'total_lb_tackles' : {'position': ['LB'], 'stat': ['defensiveTotalTackles']},
    'total_de_tackles' : {'position': ['DE'], 'stat': ['defensiveTotalTackles']},
    'total_lb_and_de_tackles' : {'position': ['LB', 'DE'], 'stat': ['defensiveTotalTackles']},
    'total_sacks' : {'position': ['LB', 'DE'], 'stat': ['defensiveSacks']},
    'total_rb_and_wr_yards' : {'position': ['RB', 'WR'], 'stat': ['rushingYards', 'receivingYards']},
    'most_te_receiving_yards' : {'position': ['TE'], 'stat': ['receivingYards']},
    'most_wr_receiving_yards' : {'position': ['WR'], 'stat': ['receivingYards']},
    'most_rb_receiving_yards' : {'position': ['RB'], 'stat': ['receivingYards']},
    'total_rb_and_wr_tds' : {'position': ['RB', 'WR'], 'stat': ['rushingTouchdowns', 'receivingTouchdowns']},
    'total_rb_carries' : {'position': ['RB'], 'stat': ['rushingAttempts']}
    }