name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov fantasy_app
        env:
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          SWID: ${{ secrets.SWID }}
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3.1.0

        with:
          gcov_ignore: fantasy_app/espn_api_submodule
